<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UsageMonitor.Core\UsageMonitor.Core.csproj" />
    <ProjectReference Include="..\UsageMonitor.LocalApi\UsageMonitor.LocalApi.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>usage-monitor</AssemblyName>
    <RootNamespace>UsageMonitor.Cli</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
